# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLIPmuzQN-vCnA9VU2Kljbk2TOGPvLP8
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Create dummy data resembling the StudentsPerformance.csv dataset for execution
data = {
    'gender': ['female', 'male', 'female', 'male', 'female'] * 200,
    'race/ethnicity': ['group B', 'group C', 'group B', 'group A', 'group C'] * 200,
    'parental level of education': ["associate's degree", "some college", "master's degree", "associate's degree", "some college"] * 200,
    'lunch': ['standard', 'standard', 'standard', 'free/reduced', 'standard'] * 200,
    'test preparation course': ['none', 'completed', 'none', 'none', 'completed'] * 200,
    'math score': [72, 69, 90, 47, 76] * 200,
    'reading score': [72, 90, 95, 57, 78] * 200,
    'writing score': [74, 88, 93, 44, 75] * 200
}
df = pd.DataFrame(data)

scores = ["math score", "reading score", "writing score"]

# 1. Grouped bar chart: parental education
edu = df.groupby("parental level of education")[scores].mean().reindex([
    "high school", "some high school", "some college",
    "associate's degree", "bachelor's degree", "master's degree"
]).dropna()
edu.plot(kind="bar", figsize=(11,6))
plt.title("Average Scores by Parental Education Level")
plt.xlabel("Parental education level")
plt.ylabel("Average score")
plt.xticks(rotation=25, ha="right")
plt.tight_layout()
plt.savefig("parental_education_grouped_bar.png", dpi=180)
plt.close()

# 2. Grouped bar chart: lunch
lunch = df.groupby("lunch")[scores].mean().reindex(["free/reduced", "standard"])
lunch.plot(kind="bar", figsize=(8,6))
plt.title("Average Scores by Lunch Type")
plt.xlabel("Lunch type")
plt.ylabel("Average score")
plt.tight_layout()
plt.savefig("lunch_grouped_bar.png", dpi=180)
plt.close()

# 3. Box plots: test preparation vs scores
fig, axes = plt.subplots(1, 3, figsize=(15,5))
for ax, score in zip(axes, scores):
    sns.boxplot(data=df, x="test preparation course", y=score, ax=ax)
    ax.set_title(score.title())
    ax.set_xlabel("Test preparation")
    ax.set_ylabel("Score")
plt.tight_layout()
plt.savefig("test_preparation_boxplots.png", dpi=180)
plt.close()

# 4. Scatter plots
pairs = [("math score","reading score"),("math score","writing score"),("reading score","writing score")]
fig, axes = plt.subplots(1, 3, figsize=(15,5))
for ax, (x, y) in zip(axes, pairs):
    sns.scatterplot(data=df, x=x, y=y, alpha=.55, ax=ax)
    ax.set_title(f"{x.title()} vs {y.title()}")
plt.tight_layout()
plt.savefig("score_scatter_plots.png", dpi=180)
plt.close()

# 5. Correlation heatmap
plt.figure(figsize=(7,6))
sns.heatmap(df[scores].corr(), annot=True, fmt=".2f", vmin=-1, vmax=1, square=True)
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.savefig("correlation_heatmap.png", dpi=180)
plt.close()

print("All requested plots generated.")